### ISSUE TITLE
My App reject used iHas App  

### ISSUE THREAD

**Issue by DavidYangNO1** [danielamitay/iHasApp#34]
We also found that your app uses public APIs in a manner not prescribed by Apple, which is not in compliance with the iOS Developer Program License Agreement, as required by the App Store Review Guidelines.

In particular, section 3.3.1 of the iOS Developer Program License Agreement specifies:

"Applications may only use Documented APIs in the manner prescribed by Apple and must not use or call any private APIs"

Specifically, we found that this app checks for all apps installed on this device by scanning all known URL schemes using a service called iHasApp.

**Comment by danielamitay** [comment]
Yes, unfortunately Apple has decided to crack down on excessive -canOpenUrl: usage. As outlined in the README, iHasApp was originally a "proof of concept."

As indicated by the intentional omission of an API to list a user's installed apps, it is clear that Apple does not wish for there to be a straightforward way to determine that information. The "URL scheme" loophole has existed

**Comment by danielamitay** [comment]
Yes, unfortunately Apple has decided to crack down on excessive -canOpenUrl: usage. As outlined in the README, iHasApp was originally a "proof of concept."

As indicated by the intentional omission of an API to list a user's installed apps, it is clear that Apple does not wish for there to be a straightforward way to determine that information. The "URL scheme" loophole and iHasA

**Comment by danielamitay** [comment]
Yes, unfortunately Apple has decided to crack down on excessive -canOpenUrl: usage. As outlined in the README, iHasApp was originally a "proof of concept."

As indicated by the intentional omission of an API to list a user's installed apps, it is clear that Apple does not wish for there to be a straightforward way to determine that information. The "URL scheme" loophole and iHasApp have existed and not been banned for ever four years now, which I would consider the real surprise. 

I am currently talking with Apple, and would of course love for URL scheme detection to be permitted (or a new API to be created), though I doubt that would occur. It is clear that Apple does not want 3rd parties to have user's app ownership information.

**Comment by shannonchou** [comment]
mine has been rejected too
